- name: Desplegar un servidor usando Podman en VM azure
  hosts: webserver
  become: yes
  tasks:
    - name: Comprobamos estado del sistema
      apt:
        update_cache: 'yes'
    - name: Subimos y ejecutamos un webserver en contendor podman
      command: podman run -d --name web_server -p 80:80 docker.io/library/httpd:latest
