- name: Deploy Nginx to AKS
  hosts: aks_cluster
  become: yes
  tasks:
    - name: Apply Nginx deployment and service
      kubernetes.core.k8s:
        state: present
        src: nginx-deployment.yml
        kubeconfig: ~/.kube/config
