- name: Playbook para instalar y iniciar Apache en localhost
  hosts: localhost
  connection: local
  tasks:
    - name: Actualizar el caché de apt
      ansible.builtin.apt:
        update_cache: yes

    - name: Instalar Apache
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Iniciar el servicio de Apache
      ansible.builtin.systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Verificar que Apache está funcionando
      ansible.builtin.command: systemctl status apache2
      register: apache_status

    - name: Mostrar el estado de Apache
      ansible.builtin.debug:
        msg: "El estado de Apache es: {{ apache_status.stdout }}"
