---
- name: Instalar Podman en la VM de Ubuntu
  hosts: vmUbuntuagg
  become: true
  tasks:
    - name: Actualizar los repositorios de apt
      apt:
        update_cache: yes

    - name: Instalar las dependencias necesarias
      apt:
        name: 
          - software-properties-common
        state: present

    - name: Añadir el repositorio de Podman
      apt_repository:
        repo: "ppa:projectatomic/ppa"
        state: present

    - name: Instalar Podman
      apt:
        name: podman
        state: present
